from turtle import Turtle, Screen
timmy = Turtle()
print(timmy)
timmy.shape('turtle')
timmy.color('crimson')
timmy.forward(100)
timmy.left(90)
timmy.forward(100)
timmy.left(90)
timmy.forward(100)
timmy.left(90)
timmy.forward(100)
timmy.forward(200)

timmy.right(90)
timmy.forward(50)
timmy.left(90)
timmy.forward(30)
timmy.right(90)
timmy.forward(50)
timmy.left(90)
timmy.forward(30)
timmy.left(90)
timmy.forward(200)
timmy.left(90)
timmy.forward(30)
timmy.left(90)
timmy.forward(50)
timmy.right(90)
timmy.forward(30)
timmy.left(90)
timmy.forward(50)
timmy.right(90)
timmy.forward(233)
timmy.right(90)
timmy.forward(100)
timmy.left(90)
timmy.forward(33)
timmy.left(90)
timmy.forward(100)
timmy.right()


my_screen = Screen()
print(my_screen)
my_screen.exitonclick()
# from prettytable import PrettyTable

# table = PrettyTable()
# table.add_column("Pokemon Name", ["Pikachu","Squirrel","Charmane"])
# table.add_column("Type",["Electric","Water","Fire"])
# table.add_column("Color",["Red","Green","Blue"])
# table.align="l"
# # table.align="c"
# # table.border=False
#
# # print(table)
# print(table.get_string())